// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/ui/pages/auth_page.dart' as a3;
import 'app/ui/pages/category_page.dart' as a4;
import 'app/ui/pages/home_page.dart' as a2;
import 'app/ui/pages/model_form_page.dart' as a0;
import 'app/ui/pages/splash_page.dart' as a1;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/ui/pages/model_form',
        uri: Uri.parse('/ui/pages/model_form'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.ModelFormPage(),
        ),
      ),
      RouteEntity(
        key: '/ui/pages/splash',
        uri: Uri.parse('/ui/pages/splash'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.SplashPage(),
        ),
      ),
      RouteEntity(
        key: '/ui/pages/home',
        uri: Uri.parse('/ui/pages/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/ui/pages/auth',
        uri: Uri.parse('/ui/pages/auth'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.AuthPage(),
        ),
      ),
      RouteEntity(
        key: '/ui/pages/category',
        uri: Uri.parse('/ui/pages/category'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.CategoryPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  ui: (
    path: '/ui',
    pages: (
      path: '/ui/pages',
      modelForm: '/ui/pages/model_form',
      splash: '/ui/pages/splash',
      home: '/ui/pages/home',
      auth: '/ui/pages/auth',
      category: '/ui/pages/category',
    ),
  ),
);
